import React, { useState, useEffect } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

interface Props { supabase: SupabaseClient }

export default function SEOScreen({ supabase }: Props) {
  const [settings, setSettings] = useState<Record<string, any>>({});
  const [msg, setMsg] = useState("");

  useEffect(() => { loadSettings(); }, []);

  async function loadSettings() {
    const { data } = await supabase.from("site_settings").select("*");
    if (data) {
      const map: Record<string, any> = {};
      data.forEach((s: any) => { map[s.key] = s.value; });
      setSettings(map);
    }
  }

  async function save(key: string, value: any) {
    const { error } = await supabase.from("site_settings").upsert(
      { key, value, updated_at: new Date().toISOString() },
      { onConflict: "key" }
    );
    if (error) setMsg(`Error: ${error.message}`);
    else { setMsg("Saved"); setTimeout(() => setMsg(""), 2000); }
  }

  const seo = settings.seo ?? {};

  return (
    <div className="space-y-8 max-w-3xl">
      {msg && (
        <div className={`px-4 py-2 rounded-lg text-[13px] font-medium ${msg.startsWith("Error") ? "bg-red-500/10 text-red-400" : "bg-green-500/10 text-green-400"}`}>
          {msg}
        </div>
      )}

      {/* Google Analytics */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Google Analytics</h3>
        <p className="text-[12px] text-[#555] mb-4">Enter your GA4 Measurement ID (e.g. G-XXXXXXXXXX)</p>
        <FieldRow label="Measurement ID" defaultValue={seo.ga_id ?? ""} onSave={(v) => save("seo", { ...seo, ga_id: v })} placeholder="G-XXXXXXXXXX" />
      </section>

      {/* Default Meta */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Default Meta Tags</h3>
        <p className="text-[12px] text-[#555] mb-4">Used when pages don't specify their own.</p>
        <div className="space-y-4">
          <FieldRow label="Site Title" defaultValue={seo.default_title ?? "Product Impact — AI product news, releases, and case studies"} onSave={(v) => save("seo", { ...seo, default_title: v })} />
          <div>
            <label className="block text-[12px] font-medium text-[#888] mb-1.5">Site Description</label>
            <TextareaRow defaultValue={seo.default_description ?? "AI product impact — news, releases, and case studies about the products transforming how we work and industries."} onSave={(v) => save("seo", { ...seo, default_description: v })} />
          </div>
          <FieldRow label="Twitter Handle" defaultValue={seo.twitter_handle ?? "@productimpactpod"} onSave={(v) => save("seo", { ...seo, twitter_handle: v })} placeholder="@handle" />
        </div>
      </section>

      {/* OG Image */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Default OG Image</h3>
        <p className="text-[12px] text-[#555] mb-4">Fallback social share image (1200x628 recommended).</p>
        <FieldRow label="OG Image URL" defaultValue={seo.og_image ?? "/og-default.png"} onSave={(v) => save("seo", { ...seo, og_image: v })} />
        {(seo.og_image || "/og-default.png") && (
          <div className="mt-3 rounded-lg overflow-hidden border border-[#222] max-w-md">
            <img src={seo.og_image || "/og-default.png"} alt="OG preview" className="w-full" />
          </div>
        )}
      </section>

      {/* Favicon */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Favicon</h3>
        <p className="text-[12px] text-[#555] mb-4">Generated by the brand asset pipeline from src/brand/. Run <code className="text-[#ff6b4a]">npm run build:assets</code> to regenerate.</p>
        <div className="flex items-center gap-4 p-4 rounded-lg bg-[#111] border border-[#1a1a1a]">
          <img src="/favicon.png" alt="favicon" className="w-8 h-8" />
          <img src="/favicon-96.png" alt="favicon 96" className="w-12 h-12" />
          <img src="/apple-touch-icon.png" alt="apple touch" className="w-14 h-14 rounded-xl" />
          <span className="text-[12px] text-[#555]">Current favicon set</span>
        </div>
      </section>

      {/* Robots */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Robots & Indexing</h3>
        <p className="text-[12px] text-[#555] mb-4">Control search engine indexing behavior.</p>
        <div className="space-y-3">
          <CheckboxRow label="Allow search engine indexing" checked={seo.indexing_enabled !== false} onToggle={(v) => save("seo", { ...seo, indexing_enabled: v })} />
          <CheckboxRow label="Include sitemap in robots.txt" checked={seo.sitemap_in_robots !== false} onToggle={(v) => save("seo", { ...seo, sitemap_in_robots: v })} />
        </div>
      </section>

      {/* Verification */}
      <section>
        <h3 className="text-[16px] font-bold text-white mb-1">Site Verification</h3>
        <p className="text-[12px] text-[#555] mb-4">Verification codes for search consoles.</p>
        <div className="space-y-4">
          <FieldRow label="Google Search Console" defaultValue={seo.google_verification ?? ""} onSave={(v) => save("seo", { ...seo, google_verification: v })} placeholder="google-site-verification=..." />
          <FieldRow label="Bing Webmaster Tools" defaultValue={seo.bing_verification ?? ""} onSave={(v) => save("seo", { ...seo, bing_verification: v })} placeholder="msvalidate.01=..." />
        </div>
      </section>
    </div>
  );
}

function FieldRow({ label, defaultValue, onSave, placeholder }: { label: string; defaultValue: string; onSave: (v: string) => void; placeholder?: string }) {
  const [val, setVal] = useState(defaultValue);
  useEffect(() => { setVal(defaultValue); }, [defaultValue]);
  return (
    <div>
      <label className="block text-[12px] font-medium text-[#888] mb-1.5">{label}</label>
      <input
        type="text"
        className="w-full px-4 py-2.5 bg-[#111] border border-[#222] rounded-lg text-[14px] text-white focus:outline-none focus:border-[#ff6b4a]/50 transition-colors"
        value={val} onChange={(e) => setVal(e.target.value)} onBlur={() => onSave(val)} placeholder={placeholder}
      />
    </div>
  );
}

function TextareaRow({ defaultValue, onSave }: { defaultValue: string; onSave: (v: string) => void }) {
  const [val, setVal] = useState(defaultValue);
  useEffect(() => { setVal(defaultValue); }, [defaultValue]);
  return (
    <textarea
      className="w-full h-24 bg-[#111] border border-[#222] rounded-lg p-4 text-[13px] text-white focus:outline-none focus:border-[#ff6b4a]/50 resize-y"
      value={val} onChange={(e) => setVal(e.target.value)} onBlur={() => onSave(val)}
    />
  );
}

function CheckboxRow({ label, checked, onToggle }: { label: string; checked: boolean; onToggle: (v: boolean) => void }) {
  return (
    <label className="flex items-center gap-3 p-3 rounded-lg bg-[#111] border border-[#1a1a1a] cursor-pointer hover:bg-[#151515] transition-colors">
      <input type="checkbox" checked={checked} onChange={(e) => onToggle(e.target.checked)}
        className="w-4 h-4 rounded border-[#333] bg-[#0a0a0a] text-[#ff6b4a] focus:ring-[#ff6b4a]/30" />
      <span className="text-[13px] text-[#ccc]">{label}</span>
    </label>
  );
}
